name: CaymanLife
favicon: null
layout_spectrum: 0.7754436822142452
typography_spectrum: 0.27856747969053686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7304234819021076
  lightness: 0.6028525838628411
  saturation: 0.48256984050385654
  rhythmicContrast: 0.7083005993627012
purpose: []
